### ISSUE TITLE
caliper benchmark question

### ISSUE THREAD

**Issue by Xubin-source** [FISCO-BCOS/FISCO-BCOS#1935] opened 2021-05-12 12:34 UTC
[caliper-flow] 	Error: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at ClientOrchestrator.init (/home/drtts1/benchmarks/node_modules/@hyperledger/caliper-core/lib/client/client-orchestrator.js:41:24)
    at Object.module.exports.run (/home/drtts1/benchmarks/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:106:60)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

![2021-05-12 20-33-43屏幕截图](https://user-images.githubusercontent.com/56347756/117975598-6acdbd80-b361-11eb-97e0-f66cdea0d6f2.png)

**Comment by cyjseagull** [comment] 2021-06-28 04:02
请参考 [#1248](https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1248),  更详细的压测说明请参考[文档](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/stress_testing.html)

**Comment by cyjseagull** [comment] 2021-06-28 04:22
#1248

**Comment by cyjseagull** [comment] 2021-06-28 04:33
Duplicate of #1248

**Closed** 2021-06-28 04:33 UTC
Labels: caliper, question
